#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
import numpy as np
from enum import Enum
from std_msgs.msg import UInt8
from std_srvs.srv import SetBool
import math

from geometry_msgs.msg import Twist, PoseStamped # /pose topic'i için eklendi
from nav_msgs.msg import OccupancyGrid

class AStarNode:
    """A helper node class for the A* pathfinding algorithm."""
    def __init__(self, parent=None, position=None):
        self.parent = parent
        self.position = position
        self.g = 0
        self.h = 0
        self.f = 0

    def __eq__(self, other):
        return self.position == other.position
    
class ExplorationState(Enum):
    EXPLORING = 1
    NAVIGATING = 2
    COMPLETED = 3
    PAUSED = 4

class FrontierExplorer(Node):
    def __init__(self):
        super().__init__('frontier_explorer_node')
        
        # =========================================================================
        # 1. ROS 2 TOPIC INTERFACES
        # =========================================================================
        # Subscribe to the dynamically updated SLAM map
        self.map_sub = self.create_subscription(
            OccupancyGrid, 
            '/map', 
            self.map_callback, 
            10
        )
        
        # Subscribe to the robot's real-time pose/orientation
        self.pose_sub = self.create_subscription(
            PoseStamped,
            '/pose',
            self.pose_callback,
            10
        )
        
        # Publish velocity commands to drive the robot using the underlying controller
        self.cmd_vel_pub = self.create_publisher(
            Twist, 
            '/cmd_vel', 
            10
        )

        self.exploration_state_pub = self.create_publisher(
            UInt8, 
            '/exploration_state', 
            10
        )
            

        self.pause_serv = self.create_service(SetBool, '/pause_exploration', self.pause_callback)
        
        # =========================================================================
        # 2. CONTROL LOOP TIMERS & STATE MACHINE
        # =========================================================================
        self.control_timer = self.create_timer(0.1, self.control_loop)
        self.state = ExplorationState.EXPLORING # Internal states: 'EXPLORING', 'NAVIGATING', 'COMPLETED'
        
        # =========================================================================
        # 3. MAP & NAVIGATION VARIABLES
        # =========================================================================
        self.grid_map = None 
        self.map_width = 0
        self.map_height = 0
        self.resolution = 0.0
        
        # Robot positions tracked in grid cells (Updated dynamically via SLAM /pose)
        self.robot_grid_x = 0
        self.robot_grid_y = 0
        self.robot_yaw = 0.0 # Orientation angle in radians
        
        self.current_path = []
        
        self.get_logger().info('--- AUTONOMOUS EXPLORATION & PATHFINDING ENGINE ONLINE ---')

    def pose_callback(self, msg):
        """Extracts real-time positioning and tracking yaw angles from the SLAM feedback loop."""
        # Convert absolute spatial coordinates straight into grid cells
        if self.resolution > 0.0:
            self.robot_grid_x = int(abs(msg.pose.position.x) / self.resolution)
            self.robot_grid_y = int(abs(msg.pose.position.y) / self.resolution)
        
        # Quaternion to Euler transform (Extracting the Yaw steering angle)
        q = msg.pose.orientation
        siny_cosp = 2.0 * (q.w * q.z + q.x * q.y)
        cosy_cosp = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
        self.robot_yaw = math.atan2(siny_cosp, cosy_cosp)

    def map_callback(self, msg):
        """Processes incoming OccupancyGrid maps generated by the SLAM toolbox."""
        self.map_width = msg.info.width
        self.map_height = msg.info.height
        self.resolution = msg.info.resolution
        self.grid_map = np.array(msg.data).reshape((self.map_height, self.map_width))

    def control_loop(self):
        """Main periodic finite-state machine handling navigation tasks."""
        self.exploration_state_pub.publish(UInt8(data=self.state.value))
        if self.grid_map is None:
            return

        if self.state == ExplorationState.EXPLORING:
            frontiers = self.find_frontiers()
            best_target = self.select_best_frontier(frontiers)
            
            if best_target:
                self.get_logger().info(f'Selected optimal frontier target cell at: {best_target}')
                start_pos = (self.robot_grid_x, self.robot_grid_y)
                
                self.current_path = self.a_star_pathfind(start_pos, best_target)
                
                if self.current_path and len(self.current_path) > 1:
                    self.state = ExplorationState.NAVIGATING
                    self.current_path.pop(0) 
            else:
                self.state = ExplorationState.COMPLETED
                self.get_logger().info('Maze fully mapped. No additional frontiers discovered.')
                self.stop_robot()

        elif self.state == ExplorationState.NAVIGATING:
            self.navigate_along_path()

    def navigate_along_path(self):
        """Generates proactive Twist signals to track calculated route waypoints."""
        if not self.current_path:
            self.state = ExplorationState.EXPLORING
            return
            
        target_x, target_y = self.current_path[0]
        
        dx = target_x - self.robot_grid_x
        dy = target_y - self.robot_grid_y
        distance_to_target = math.sqrt(dx**2 + dy**2)
        
        if distance_to_target < 1.0: 
            self.current_path.pop(0)
            if not self.current_path:
                self.state = ExplorationState.EXPLORING
                self.stop_robot()
                return
            return

        desired_heading = math.atan2(dy, dx)
        heading_error = desired_heading - self.robot_yaw
        heading_error = math.atan2(math.sin(heading_error), math.cos(heading_error))
        
        twist_msg = Twist()
        if abs(heading_error) > 0.4:
            twist_msg.linear.x = 0.0
            twist_msg.angular.z = 0.4 if heading_error > 0 else -0.4
        else:
            twist_msg.linear.x = 0.15 
            twist_msg.angular.z = 0.5 * heading_error
            
        self.cmd_vel_pub.publish(twist_msg)

    def find_frontiers(self):
        """Scans the matrix array for free cells adjacent to unknown territory bounds."""
        frontiers = []
        for y in range(1, self.map_height - 1):
            for x in range(1, self.map_width - 1):
                if self.grid_map[y, x] == 0: 
                    neighbors = [
                        self.grid_map[y+1, x], self.grid_map[y-1, x],
                        self.grid_map[y, x-1], self.grid_map[y, x+1]
                    ]
                    if -1 in neighbors: 
                        frontiers.append((x, y))
        return frontiers

    def select_best_frontier(self, frontiers):
        """Finds closest valid candidate via heuristic tracking checks."""
        if not frontiers:
            return None
        best_frontier = None
        min_distance = float('inf')
        for fx, fy in frontiers:
            distance = abs(fx - self.robot_grid_x) + abs(fy - self.robot_grid_y)
            if distance < min_distance:
                min_distance = distance
                best_frontier = (fx, fy)
        return best_frontier

    def a_star_pathfind(self, start, goal):
        """Modified A* implementation configured to match dynamic OccupancyGrid inputs directly."""
        open_list = []
        closed_list = []

        start_node = AStarNode(None, start)
        end_node = AStarNode(None, goal)
        open_list.append(start_node)

        move_directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

        while open_list:
            current_node = min(open_list, key=lambda o: o.f)
            open_list.remove(current_node)
            closed_list.append(current_node)

            if current_node == end_node:
                path = []
                current = current_node
                while current is not None:
                    path.append(current.position)
                    current = current.parent
                return path[::-1]

            for r_offset, c_offset in move_directions:
                node_position = (current_node.position[0] + r_offset, current_node.position[1] + c_offset)

                if (node_position[0] >= self.map_width or node_position[0] < 0 or
                    node_position[1] >= self.map_height or node_position[1] < 0):
                    continue

                if self.grid_map[node_position[1], node_position[0]] >= 50:
                    continue

                child = AStarNode(current_node, node_position)
                if child in closed_list:
                    continue

                child.g = current_node.g + 1
                child.h = abs(child.position[0] - end_node.position[0]) + abs(child.position[1] - end_node.position[1])
                child.f = child.g + child.h

                if any(open_node for open_node in open_list if child == open_node and child.g >= open_node.g):
                    continue

                open_list.append(child)
        return []
    
    def pause_callback(self, request, response):
        """Service callback to pause or resume exploration."""
        if request.data:
            self.state = ExplorationState.PAUSED
            self.stop_robot()
            response.success = True
            response.message = "Exploration paused."
        else:
            self.state = ExplorationState.EXPLORING
            response.success = True
            response.message = "Exploration resumed."
        return response

    def stop_robot(self):
        twist_msg = Twist()
        twist_msg.linear.x = 0.0
        twist_msg.angular.z = 0.0
        self.cmd_vel_pub.publish(twist_msg)

def main(args=None):
    rclpy.init(args=args)
    node = FrontierExplorer()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info('Autonomous exploration suspended.')
    finally:
        node.stop_robot()
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()